language: node_js
node_js:
  - '10'
  - '12'
  - '14'
install:
  - npm install -g coveralls
  - npm install
script:
  - npm run lint
  - npm run type-check
  - npm run test:cover
  - cat ./coverage/lcov.info | coveralls
